<a href="https://colab.research.google.com/github/Harsh-Patel25/Python/blob/main/daily_lessons/Day_8_Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🚀 Day‑8 Lesson: Python NumPy Arrays

Welcome to Day‑8! Today, we'll explore **NumPy**—the backbone of scientific computing in Python. This lesson covers everything from the basics to ML-related examples, with extra samples to solidify your learning.

---

## 1. Introduction to NumPy Arrays

### 🔍 What is NumPy?
**NumPy** is a powerful package for scientific computing in Python. It provides a high-performance, multidimensional array object (`ndarray`) and a suite of functions to work with these arrays efficiently.

### ⚡ Key Advantages Over Lists:
- **Data Type Consistency:**  
  NumPy arrays contain elements of the same data type, which boosts performance for numerical operations.
- **Performance:**  
  Array operations are executed in C, making them much faster than Python lists.
- **Memory Efficiency:**  
  Arrays are stored in a compact, homogeneous format.

---

### 💻 Example 1: Converting a List to a NumPy Array

```python
import numpy as np

# Convert a Python list to a NumPy array
lst = [1, 2, 3, 4]
arr = np.array(lst)
print("Array:", arr)
print("Type:", type(arr))  # Output: <class 'numpy.ndarray'>
print("Shape:", arr.shape)  # Output: (4,)
```

**Expected Output:**

```
Array: [1 2 3 4]
Type: <class 'numpy.ndarray'>
Shape: (4,)
```

**Extra Examples:**

1. **Array with Mixed Data Types:**
   ```python
   lst_mixed = [1, 2, 3, 4.5]  # Mixed int and float
   arr_mixed = np.array(lst_mixed)
   print("Mixed Array:", arr_mixed)  # All elements converted to float
   ```
   
   **Expected Output:**
   ```
   Mixed Array: [1.  2.  3.  4.5]
   ```

2. **Creating an Array from a Tuple:**
   ```python
   tpl = (5, 6, 7, 8)
   arr_from_tuple = np.array(tpl)
   print("Array from tuple:", arr_from_tuple)
   ```
   
   **Expected Output:**
   ```
   Array from tuple: [5 6 7 8]
   ```

3. **2D Array (Matrix) Creation:**
   ```python
   lst1 = [1, 2, 3, 4, 5]
   lst2 = [2, 3, 4, 5, 6]
   lst3 = [3, 4, 5, 6, 7]
   arr2d = np.array([lst1, lst2, lst3])
   print("2D Array:\n", arr2d)
   print("Shape:", arr2d.shape)  # Output: (3, 5)
   ```
   
   **Expected Output:**
   ```
   2D Array:
    [[1 2 3 4 5]
     [2 3 4 5 6]
     [3 4 5 6 7]]
   Shape: (3, 5)
   ```

4. **ML Connection Example:**
   In ML, datasets are often represented as a 2D array (rows as samples, columns as features):
   ```python
   features = np.array([[5.1, 3.5, 1.4, 0.2],
                        [4.9, 3.0, 1.4, 0.2],
                        [6.2, 3.4, 5.4, 2.3]])
   print("Feature matrix:\n", features)
   print("Shape:", features.shape)  # e.g., (3, 4)
   ```
   
   **Expected Output:**
   ```
   Feature matrix:
    [[5.1 3.5 1.4 0.2]
     [4.9 3.  1.4 0.2]
     [6.2 3.4 5.4 2.3]]
   Shape: (3, 4)
   ```

---

## 2. Indexing and Slicing Arrays

### 🔑 Indexing
Access individual elements using square brackets—similar to Python lists.

#### 👉 Example 2: Indexing a 1D Array
```python
print("Element at index 3:", arr[3])  # Output: 4
arr[3] = 5
print("Modified Array:", arr)  # Output: [1, 2, 3, 5]
print("Last element (using negative index):", arr[-1])  # Output: 5
```

**Expected Output:**
```
Element at index 3: 4
Modified Array: [1 2 3 5]
Last element (using negative index): 5
```

### ✂️ Slicing
Extract a subset of an array with slicing.
```python
print("Sliced array (all but last element):", arr[:-1])  # Output: [1, 2, 3]
print("Reverse slicing with step -3:", arr[::-3])  # Every 3rd element from the end
```

**Expected Output:**
```
Sliced array (all but last element): [1 2 3]
Reverse slicing with step -3: [5 1]
```

**Extra Examples:**

1. **Slicing a 2D Array:**
   ```python
   # Get all rows, columns from index 3 to end
   sliced_arr2d = arr2d[:, 3:]
   print("Sliced 2D Array:\n", sliced_arr2d)
   print("Shape:", sliced_arr2d.shape)  # Output: (3, 2)
   ```
   
   **Expected Output:**
   ```
   Sliced 2D Array:
    [[4 5]
     [5 6]
     [6 7]]
   Shape: (3, 2)
   ```

2. **Advanced Slicing:**
   ```python
   # Submatrix: from row 1 onward, columns 1 to 3 (excludes index 3)
   submatrix = arr2d[1:, 1:3]
   print("Submatrix:\n", submatrix)
   ```
   
   **Expected Output:**
   ```
   Submatrix:
    [[3 4]
     [4 5]]
   ```

3. **Indexing with Boolean Masks:**
   ```python
   # Create a boolean mask to filter elements less than 3 in a 1D array
   mask = arr < 3
   print("Boolean Mask:", mask)
   print("Filtered Elements:", arr[mask])
   ```
   
   **Expected Output:**
   ```
   Boolean Mask: [ True  True False False] # Array: [1 2 3 4]
   Filtered Elements: [1 2]
   ```

4. **ML Connection Example:**
   In feature selection, you might only select specific columns:
   ```python
   # Select the first two features from the dataset
   selected_features = features[:, :2]
   print("Selected Features:\n", selected_features)
   ```
   
   **Expected Output:**
   ```
   Selected Features:
    [[5.1 3.5]
     [4.9 3. ]
     [6.2 3.4]]
   ```

---

## 3. Array Reshaping and Creation Methods

### 🔄 Reshaping Arrays
Reshape arrays without altering their data.

#### 👉 Example 3: Reshaping a 2D Array
```python
reshaped_arr = arr2d.reshape(5, 3)  # Total elements must match
print("Reshaped Array:\n", reshaped_arr)
```

**Expected Output:**  
*Flattening `arr2d = [[1,2,3,4,5], [2,3,4,5,6], [3,4,5,6,7]]` gives*  
```
Reshaped Array:
 [[1 2 3]
  [4 5 2]
  [3 4 5]
  [6 3 4]
  [5 6 7]]
```

**Extra Examples:**

1. **Reshaping a 1D Array:**
   ```python
   arr_reshaped = arr.reshape(2, 2)
   print("Reshaped 1D Array to 2x2:\n", arr_reshaped)
   ```
   
   **Expected Output:**
   ```
   Reshaped 1D Array to 2x2:
    [[1 2]
     [3 5]]
   ```

2. **Using `np.arange`:**
   ```python
   # Create an array with numbers from 1 to 19 (step 2), then reshape it
   arr_arange = np.arange(1, 20, 2).reshape(2, 5)
   print("Array using arange:\n", arr_arange)
   ```
   
   **Expected Output:**
   ```
   Array using arange:
    [[ 1  3  5  7  9]
     [11 13 15 17 19]]
   ```

3. **Extra 3D Example:**
   ```python
   # Reshape an arange array into a 3D array
   arr_3d = np.arange(1, 21).reshape(2, 5, 2)
   print("3D Array:\n", arr_3d)
   print("Shape:", arr_3d.shape)

   # reshape(2, 5, 2) changes the shape of the 1D array into a 3D array.
Parameters Explained:
2: The new array will have 2 blocks (or layers).
5: Each block will have 5 rows.
2: Each row will have 2 columns.
Total Elements Check:
The original array has 20 elements. The new shape (2 x 5 x 2) equals 2 * 5 * 2 = 20 elements, so the reshape is valid
   ```
   
   **Expected Output:**
   ```
   3D Array:
    [[[ 1  2]
      [ 3  4]
      [ 5  6]
      [ 7  8]
      [ 9 10]]
   
     [[11 12]
      [13 14]
      [15 16]
      [17 18]
      [19 20]]]
   Shape: (2, 5, 2)
   ```

4. **ML Connection Example:**
   In deep learning, images are reshaped into tensors:
   ```python
   # Reshape a grayscale image of 28x28
   image = np.arange(784).reshape(28, 28)
   print("Image Shape:", image.shape)
   ```
   
   **Expected Output:**
   ```
   Image Shape: (28, 28)
   ```

---

## 4. Arithmetic Operations on Arrays

### 🔢 Basic Arithmetic Operations
Perform fast, element-wise mathematical computations with NumPy.

#### 👉 Example 4: Basic Arithmetic
```python
# Element-wise multiplication
result = arr * arr
print("Element-wise multiplication:", result)

# For a 2D array
result2d = arr2d * arr2d
print("Element-wise multiplication of 2D array:\n", result2d)
```

**Expected Output:**

For the 1D array `arr = [1, 2, 3, 5]`:
```
Element-wise multiplication: [ 1  4  9 25]
```

For the 2D array `arr2d = [[1,2,3,4,5],
                           [2,3,4,5,6],
                           [3,4,5,6,7]]`:
```
Element-wise multiplication of 2D array:
 [[ 1  4  9 16 25]
  [ 4  9 16 25 36]
  [ 9 16 25 36 49]]
```

**Extra Examples:**

1. **Addition and Subtraction:**
   ```python
   print("Addition:", arr + 10)  # Adds 10 to every element
   print("Subtraction:", arr - 2)  # Subtracts 2 from every element
   ```
   
   **Expected Output:**
   ```
   Addition: [11 12 13 15]
   Subtraction: [-1  0  1  3]
   ```

2. **Division and Exponentiation:**
   ```python
   print("Division:", arr / 2)  # Divides each element by 2
   print("Exponentiation:", arr ** 2)  # Squares each element
   ```
   
   **Expected Output:**
   ```
   Division: [0.5 1.  1.5 2.5]
   Exponentiation: [ 1  4  9 25]
   ```

3. **Using Universal Functions (ufuncs):**
   ```python
   print("Square Root:", np.sqrt(arr))  # Computes square root element-wise
   print("Logarithm:", np.log(arr))     # Computes natural log element-wise
   ```
   
   **Expected Output:**  
   *(Values approximated)*
   ```
   Square Root: [1.         1.41421356 1.73205081 2.23606798]
   Logarithm: [0.         0.69314718 1.09861229 1.60943791]
   ```

4. **ML Connection Example:**
   Element-wise operations help compute errors in neural networks:
   ```python
   predictions = np.array([0.1, 0.4, 0.5])
   targets = np.array([0, 1, 1])
   error = np.abs(predictions - targets)
   print("Absolute error:", error)
   ```
   
   **Expected Output:**
   ```
   Absolute error: [0.1 0.6 0.5]
   ```

---

## 5. Creating Special Arrays

### 🎨 Special Array Creation Functions
NumPy makes it easy to create arrays for various purposes.

#### 👉 Example 5: Using `ones`, `zeros`, and `arange`
```python
ones_array = np.ones((5, 3))
print("Ones Array:\n", ones_array)

zeros_array = np.zeros((4, 5))
print("Zeros Array:\n", zeros_array)
```

**Expected Output:**

For `ones_array` (5×3):
```
Ones Array:
 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]
```

For `zeros_array` (4×5):
```
Zeros Array:
 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]
```

**Extra Examples:**

1. **Random Integer Array:**
   ```python
   random_ints = np.random.randint(10, 50, 4).reshape(2, 2)
   print("Random Integer Array:\n", random_ints)
   ```
   
   **Expected Output:**  
   *(Note: Output will vary since values are random. For example:)*
   ```
   Random Integer Array:
   [[12 37]
    [45 29]]
   ```

2. **Random Normal Distribution:**
   ```python
   random_normal = np.random.randn(5, 6)
   print("Random Normal Array:\n", random_normal)
   ```
   
   **Expected Output:**  
   *(Values will vary. Example:)*
   ```
   Random Normal Array:
   [[ 0.50 -1.20  0.33  0.87 -0.45  1.02]
    [ ...  ...  ...  ...  ...  ... ]
    [...]]
   ```

3. **Random Sample Array:**
   ```python
   random_sample = np.random.random_sample((4, 7))
   print("Random Sample Array:\n", random_sample)
   ```
   
   **Expected Output:**  
   *(Values will vary. Example:)*
   ```
   Random Sample Array:
   [[0.234, 0.678, ...],
    [...],
    [...],
    [...]]
   ```

4. **ML Connection Example:**
   Generate synthetic data for ML testing:
   ```python
   # Create a random feature matrix for 100 samples and 10 features
   synthetic_data = np.random.rand(100, 10)
   print("Synthetic Data Shape:", synthetic_data.shape)
   ```
   
   **Expected Output:**
   ```
   Synthetic Data Shape: (100, 10)
   ```

---

## 6. Exploratory Data Analysis (EDA) Using NumPy

### 🔍 Using NumPy for EDA
Leverage NumPy's powerful filtering and reshaping capabilities for data analysis.

#### 👉 Example 6: Filtering and Reshaping
```python
# Filter elements less than 2 in a 1D array
filtered = arr[arr < 2]
print("Filtered elements (arr < 2):", filtered)
```

**Expected Output:**
```
Filtered elements (arr < 2): [1]
```

**Extra Examples:**

1. **Reshaping for Analysis:**
   ```python
   reshaped = arr2d.reshape(5, 3)
   print("Reshaped Array for EDA:\n", reshaped)
   ```
   
   **Expected Output:**  
   *(Same as previous reshaping example)*
   ```
   Reshaped Array for EDA:
    [[1 2 3]
     [4 5 2]
     [3 4 5]
     [6 3 4]
     [5 6 7]]
   ```

2. **Boolean Masking:**
   ```python
   # Apply a boolean mask on a 2D array (select elements > 4)
   mask = arr2d > 4
   print("Boolean Mask on 2D Array:\n", mask)
   print("Filtered 2D Array:", arr2d[mask])
   ```
   
   **Expected Output:**
   ```
   Boolean Mask on 2D Array:
   [[False False False False  True]
    [False False False  True  True]
    [False False  True  True  True]]
   Filtered 2D Array: [5 5 6 5 6 7]
   ```

3. **Aggregations:**
   ```python
   print("Sum of arr2d:", np.sum(arr2d))
   print("Mean of arr2d:", np.mean(arr2d))
   ```
   
   **Expected Output:**
   ```
   Sum of arr2d: 60
   Mean of arr2d: 4.0
   ```

4. **ML Connection Example:**
   Filter outliers in a feature vector:
   ```python
   feature = np.array([10, 15, 20, 25, 30, 100])
   filtered_feature = feature[feature < 50]
   print("Filtered Feature Vector:", filtered_feature)
   ```
   
   **Expected Output:**
   ```
   Filtered Feature Vector: [10 15 20 25 30]
   ```

---

## 📝 Summary

- **NumPy Arrays:**  
  Efficient, homogeneous structures vital for numerical computations and ML.
- **Indexing & Slicing:**  
  Flexible methods to access and manipulate array elements.
- **Arithmetic Operations:**  
  Fast, element-wise computations for mathematical tasks.
- **Special Array Creation:**  
  Quick generation of arrays using `np.ones`, `np.zeros`, `np.arange`, and random functions.
- **EDA with NumPy:**  
  Powerful techniques to filter, reshape, and aggregate data for model training.

---

